# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_bookedition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedition',
            name='date',
            field=models.DateField(),
        ),
    ]
